In [0]:
!pip install scikit-plot

In [0]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA,TruncatedSVD

In [0]:
df= pd.read_csv("train.csv")

In [0]:
dx = pd.DataFrame(df.drop(['Activity','subject'],axis=1))
dy_label = df.Activity.values.astype(object)
from sklearn import linear_model
# Transforming non numerical labels into numerical labels
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()
# encoding train labels 
encoder.fit(dy_label)
dy = encoder.transform(dy_label)
X_train, X_test, Y_train, Y_test = train_test_split(dx,dy,test_size=0.2, random_state=4)
from sklearn.decomposition import FastICA 
ICA = FastICA(n_components=20, random_state=42)
X_train=ICA.fit_transform(X_train,Y_train)
X_test= ICA.transform(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/decomposition/fastica_.py:119: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  ConvergenceWarning)


In [0]:
#LINEAR REGRESSION
#test
reg= linear_model.LinearRegression()
reg.fit(X_test,Y_test)
reg.score(X_test,Y_test)

0.9031352540900438

In [0]:
#train
reg.fit(X_train,Y_train)
reg.score(X_train,Y_train)

0.9052362996292423

In [0]:
# Driver code 
def main(): 
      
    # Building Phase 
    data = importdata() 
    X, Y, X_train, X_test, Y_train, Y_test = splitdataset(data) 
    clf_gini = train_using_gini(X_train, X_test, Y_train) 
    clf_entropy = tarin_using_entropy(X_train, X_test, Y_train) 
      
    # Operational Phase 
    print("Results Using Gini Index:") 
      
    # Prediction using gini 
    y_pred_gini = prediction(X_test, clf_gini) 
    cal_accuracy(Y_test, y_pred_gini) 
      
    print("Results Using Entropy:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test, clf_entropy) 
    cal_accuracy(Y_test, y_pred_entropy) 
      

In [0]:
# Importing the required packages 
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.decomposition import PCA,TruncatedSVD

In [0]:
# Function importing Dataset 
def importdata(): 
    
    df= pd.read_csv("train.csv")
    return df

# Function to split the dataset 
def splitdataset(df):
    dx = pd.DataFrame(df.drop(['Activity','subject'],axis=1))
    dy_label = df.Activity.values.astype(object)
    from sklearn import linear_model
    # Transforming non numerical labels into numerical labels
    from sklearn import preprocessing
    encoder = preprocessing.LabelEncoder()
    # encoding train labels 
    encoder.fit(dy_label)
    dy = encoder.transform(dy_label)
    #PCA APPLY
    pca= PCA(n_components=40, whiten= 'True')
    x= pca.fit(dx).transform(dx)
    pca.explained_variance_
    X_train, X_test, Y_train, Y_test = train_test_split(x,dy,test_size=0.2, random_state=4)
    return x, dy, X_train, X_test, Y_train, Y_test 

In [0]:
# Function to perform training with giniIndex. 
def train_using_gini(X_train, X_test, Y_train): 
  
    # Creating the classifier object 
    clf_gini = DecisionTreeClassifier(criterion = "gini", 
            random_state = 100,max_depth=3, min_samples_leaf=5) 
  
    # Performing training 
    clf_gini.fit(X_train, Y_train) 
    return clf_gini 

In [0]:
# Function to perform training with entropy. 
def tarin_using_entropy(X_train, X_test, Y_train): 
  
    # Decision tree with entropy 
    clf_entropy = DecisionTreeClassifier( 
            criterion = "entropy", random_state = 100, 
            max_depth = 3, min_samples_leaf = 5) 
  
    # Performing training 
    clf_entropy.fit(X_train, Y_train) 
    return clf_entropy 
  

In [0]:
# Function to make predictions 
def prediction(X_test, clf_object): 
  
    # Predicton on test with giniIndex 
    y_pred = clf_object.predict(X_test) 
    print("Predicted values:") 
    print(y_pred) 
    return y_pred 

In [0]:
# Function to calculate accuracy 
def cal_accuracy(Y_test, y_pred): 
      
    print("Confusion Matrix: ", 
        confusion_matrix(Y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(Y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(Y_test, y_pred)) 

In [0]:
# Calling main function 
if __name__=="__main__": 
    main() 

Results Using Gini Index:
Predicted values:
[0 4 0 ... 1 3 3]
Confusion Matrix:  [[258   2   2   0   0   0]
 [ 10 172 102   0   0   0]
 [  0  47 229   0   0   0]
 [  0   0   0 221  19   0]
 [  0   0   0  36 142   0]
 [  0   0   0 145  76  10]]
Accuracy :  70.15635622025833
Report :                precision    recall  f1-score   support

           0       0.96      0.98      0.97       262
           1       0.78      0.61      0.68       284
           2       0.69      0.83      0.75       276
           3       0.55      0.92      0.69       240
           4       0.60      0.80      0.68       178
           5       1.00      0.04      0.08       231

    accuracy                           0.70      1471
   macro avg       0.76      0.70      0.64      1471
weighted avg       0.77      0.70      0.65      1471

Results Using Entropy:
Predicted values:
[0 5 0 ... 0 3 3]
Confusion Matrix:  [[260   0   0   0   0   2]
 [ 21 164  99   0   0   0]
 [  0  47 229   0   0   0]
 [  0   0   0 