In [0]:
!pip install scikit-plot

In [0]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [0]:
# Driver code 
def main(): 
      
    # Building Phase 
    data = importdata() 
    X, Y, X_train, X_test, Y_train, Y_test = splitdataset(data) 
    clf_gini = train_using_gini(X_train, X_test, Y_train) 
    clf_entropy = tarin_using_entropy(X_train, X_test, Y_train) 
      
    # Operational Phase 
    print("Results Using Gini Index:") 
      
    # Prediction using gini 
    y_pred_gini = prediction(X_test, clf_gini) 
    cal_accuracy(Y_test, y_pred_gini) 
      
    print("Results Using Entropy:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test, clf_entropy) 
    cal_accuracy(Y_test, y_pred_entropy) 
      

In [0]:
# Importing the required packages 
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [0]:
# Function importing Dataset 
def importdata(): 
    
    df= pd.read_csv("train.csv")
    return df

# Function to split the dataset 
def splitdataset(df):
    dx = pd.DataFrame(df.drop(['Activity','subject'],axis=1))
    dy_label = df.Activity.values.astype(object)
    from sklearn import linear_model
    # Transforming non numerical labels into numerical labels
    from sklearn import preprocessing
    encoder = preprocessing.LabelEncoder()
    # encoding train labels 
    encoder.fit(dy_label)
    dy = encoder.transform(dy_label)
    #SVD APPLY
    from sklearn.decomposition import PCA,TruncatedSVD
    svd= TruncatedSVD(n_components = 100)
    x=svd.fit(dx).transform(dx)
    X_train, X_test, Y_train, Y_test = train_test_split(x,dy,test_size=0.2, random_state=4)
    return x, dy, X_train, X_test, Y_train, Y_test 

In [0]:
# Function to perform training with giniIndex. 
def train_using_gini(X_train, X_test, Y_train): 
  
    # Creating the classifier object 
    clf_gini = DecisionTreeClassifier(criterion = "gini", 
            random_state = 100,max_depth=3, min_samples_leaf=5) 
  
    # Performing training 
    clf_gini.fit(X_train, Y_train) 
    return clf_gini 

In [0]:
# Function to perform training with entropy. 
def tarin_using_entropy(X_train, X_test, Y_train): 
  
    # Decision tree with entropy 
    clf_entropy = DecisionTreeClassifier( 
            criterion = "entropy", random_state = 100, 
            max_depth = 3, min_samples_leaf = 5) 
  
    # Performing training 
    clf_entropy.fit(X_train, Y_train) 
    return clf_entropy 
  

In [0]:
# Function to make predictions 
def prediction(X_test, clf_object): 
  
    # Predicton on test with giniIndex 
    y_pred = clf_object.predict(X_test) 
    print("Predicted values:") 
    print(y_pred) 
    return y_pred 

In [0]:
# Function to calculate accuracy 
def cal_accuracy(Y_test, y_pred): 
      
    print("Confusion Matrix: ", 
        confusion_matrix(Y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(Y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(Y_test, y_pred)) 

In [0]:
# Calling main function 
if __name__=="__main__": 
    main() 

Results Using Gini Index:
Predicted values:
[0 5 0 ... 0 3 3]
Confusion Matrix:  [[252   5   4   0   0   1]
 [  6 155 123   0   0   0]
 [  0  56 220   0   0   0]
 [  0   0   0 191  37  12]
 [  0   0   0  12 150  16]
 [  0   0   0  21  32 178]]
Accuracy :  77.906186267845
Report :                precision    recall  f1-score   support

           0       0.98      0.96      0.97       262
           1       0.72      0.55      0.62       284
           2       0.63      0.80      0.71       276
           3       0.85      0.80      0.82       240
           4       0.68      0.84      0.76       178
           5       0.86      0.77      0.81       231

    accuracy                           0.78      1471
   macro avg       0.79      0.79      0.78      1471
weighted avg       0.79      0.78      0.78      1471

Results Using Entropy:
Predicted values:
[0 5 0 ... 0 3 3]
Confusion Matrix:  [[253   5   3   0   0   1]
 [  6 156 122   0   0   0]
 [  0  56 220   0   0   0]
 [  0   0   0 17